fix ldif syntax and add idnsTemplateAttribute
freeipa/bind-dyndb-ldap pull request #2
Opened 2016-10-13 02:42 UTC by stutiredboy

schema.ldif lost some white space in the line end.
schema.ldif lost the idnsTemplateAttribute definitition

2016-10-13 06:59 UTC, MartinBasti requested changes

2016-10-13 06:59 UTC, mbasti-rh commented on doc/schema.ldif
> + EQUALITY caseIgnoreMatch
Please don't add whitespace at the end of line

2016-10-13 06:59 UTC, mbasti-rh commented on doc/schema.ldif
> +olcattributeTypes: ( 2.16.840.1.113730.3.8.5.29
You have typo there, 'olcattribute''

2016-10-13 06:59 UTC, mbasti-rh commented on doc/schema.ldif
> + SUP top
Same here, no extra whitespace please

2016-10-13 06:59 UTC, mbasti-rh commented on doc/schema.ldif
> +attributeTypes: ( 2.16.840.1.113730.3.8.5.29
Please merge this change to previous patch

2016-10-13 07:00 UTC, mbasti-rh commented
Hello, I wrote inline comments. Please set proper author name in commit (no root please)

2016-10-13 07:03 UTC, pspacek commented
@mbasti-rh , the white-space at the end of line is required here because the first space at the beginning of line will be consumed by LDIF parser. I agree that root should not be author of the commit :-)

2016-10-13 09:11 UTC, stutiredboy commented
so sorry for the root committer, but the white space is needed by OpenLDAP LDIF parser. I have fixed the ugly pull request. :-)

Thanks.

2016-10-13 10:21 UTC, pspacek approved these changes
ACK, thank you!

2016-10-14 11:01 UTC, pspacek commented
Thanks! I've commited the fix as 17711141882aca3847a5daba2292bcbcc471ec63.

2016-10-14 11:01 UTC, closed without merging